### ISSUE TITLE
unable to inject

### ISSUE THREAD

**Issue by leeterry** [Bbalduzz/Ghost-Watchers-Cheat#4]
Followed the instructions given on main page only to get Error: The DLL at the specified location was not found (yes they are all in the same folder before you ask). Tried with sharp mono injector as well (something I am more comfortable using because have used it before) by selecting the ghost watchers process, showing it where the dll is, namespace filled itself in with Ghost-Watchers-Internal, class name Loader, and method name Init. However, that also failed leaving an error saying "Injection failed: mono_class_from_name() returned NULL".  Attempted to redownload the files to be sure it was not corrupted during dl but got same results.

**Comment by 4malgama** [comment]
`MonoJabber.exe "Ghost Watchers.exe" Ghost-Watchers-Internal.dll Ghost_Watchers_Internal Loader init`
